version: "3.7"
services:
  chal:
    build: .
    container_name: "Challenge_chal_container"
    volumes:
    - ./db.sqlite3:/code/db.sqlite3
    expose:
    - "9000"
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: "Challenge_nginx_container"
    volumes:
      - "./nginx.default:/etc/nginx/conf.d/default.conf"
      - "./static:/var/www/static"
    ports:
    - "11001:80"
    networks:
      - my_network

networks:
  my_network:

