version: "3.7"
services:
  chal:
    build: .
    container_name: "<container_name>"
    volumes:
    - ./db.sqlite3:/code/db.sqlite3
    expose:
    - "9000"
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: "<chal_nginx>"
    volumes:
      - "./nginx.default:/etc/nginx/conf.d/default.conf"
      - "./static:/var/www/static"
    ports:
    - "10000:80"
    networks:
      - my_network

networks:
  my_network:

